name = "Syllabi"
uuid = "68b49f8f-4574-43ac-a1c5-b6e71211e06a"
authors = ["Matt Bhagat-Conway <matt@indicatrix.org> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
